# Generated by Django 3.0.3 on 2020-08-16 05:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200815_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2020, 8, 16, 5, 53, 27, 914025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 16, 5, 53, 27, 914025, tzinfo=utc)),
        ),
    ]
